#r "System.Runtime.Caching"
#load "ObservableExt.fs"
#load "Probability.fs"
#load "Cgp.fs"
#load "CgpRun.fs"
#r @"..\packages\Microsoft.Msagl.1.1.1\lib\net40\Microsoft.Msagl.dll"
#r @"..\packages\Microsoft.Msagl.Drawing.1.1.1\lib\net40\Microsoft.Msagl.Drawing.dll"
#r @"..\packages\Microsoft.Msagl.GraphViewerGDI.1.1.1\lib\net40\Microsoft.Msagl.GraphViewerGdi.dll"
#I @"..\FsCgpTools"
#load "GgpGraph.fs"

